/*
👋 Hi! This file was autogenerated by tslint-to-eslint-config.
https://github.com/typescript-eslint/tslint-to-eslint-config

It represents the closest reasonable ESLint configuration to this
project's original TSLint configuration.

We recommend eventually switching this configuration to extend from
the recommended rulesets in typescript-eslint. 
https://github.com/typescript-eslint/tslint-to-eslint-config/blob/master/docs/FAQs.md

Happy linting! 💖
*/

import eslint from '@eslint/js'
import prettier from 'eslint-config-prettier'
import tseslint from 'typescript-eslint'

export default tseslint.config(
  { ignores: ['node_modules'] },
  eslint.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  {
    languageOptions: {
      ecmaVersion: 'latest',
      parserOptions: {
        project: true,
        tsconfigRootDir: '.',
      },
    },
    rules: {
      'no-console': 'error',
      'no-duplicate-imports': 'warn',
      'no-magic-numbers': 0,
      '@typescript-eslint/no-base-to-string': 0,
      '@typescript-eslint/no-dynamic-delete': 1,
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-magic-numbers': [
        'warn',
        {
          ignoreArrayIndexes: true,
          ignoreTypeIndexes: true,
          ignore: [1, 0, -1],
          ignoreEnums: true,
        },
      ],
      '@typescript-eslint/no-misused-promises': 0,
      '@typescript-eslint/no-shadow': [
        'error',
        {
          hoist: 'all',
        },
      ],
      '@typescript-eslint/no-unsafe-argument': 0,
      '@typescript-eslint/no-unsafe-assignment': 0,
      '@typescript-eslint/no-unsafe-member-access': 0,
      '@typescript-eslint/no-unsafe-call': 0,
      '@typescript-eslint/no-unsafe-return': 0,
      '@typescript-eslint/no-unused-vars': 0,
      '@typescript-eslint/require-await': 0,
      '@typescript-eslint/restrict-template-expressions': 0,
    },
  },
  prettier,
  {
    files: ['test/**/*.ts'],
    rules: {
      '@typescript-eslint/no-magic-numbers': 'off',
    },
  },
)

